# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170706_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='novelty',
        ),
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=1, verbose_name='новинка'),
            preserve_default=False,
        ),
    ]
